package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class SampleController2 {
	@FXML
	private TextField textfield1;
	@FXML
	private Label label1;

	// Event Listener on Button.onAction
	@FXML
	public void letsgo(ActionEvent event) {
		// TODO Autogenerated
	}
}
